### ISSUE TITLE
[BUG] panic: interface conversion: interface {} 

### ISSUE THREAD

**Issue by quanvincss** [fido-alliance/fdo-fido-conformance-server#40]
To simplify issue resolution process, please provide network logs, and or test voucher.
```
2023/09/21 13:26:26 Starting FIDO_TEST_VOUCHER_ENTRY_BAD_HDRINFO_HASH
2023/09/21 13:26:26 Starting FIDO_TEST_VOUCHER_ENTRY_BAD_SIGNATURE
2023/09/21 13:26:26 Starting FIDO_TEST_VOUCHER_ENTRY_BAD_PREV_HASH
panic: interface conversion: interface {} is fdoshared.DeviceSgType, not *int

goroutine 83 [running]:
github.com/fido-alliance/fdo-fido-conformance-server/core/shared.GetIntRef(...)
        /Users/thaodtp/Documents/work/projects/FDO/FA/fdo-fido-conformance-server/core/shared/other.crypto.go:49
github.com/fido-alliance/fdo-fido-conformance-server/core/device.GenerateOvEntry({{}, 0x140061aa000?, {0x140000307e0?, 0x1a0?, 0xc4?}}, {{}, 0x8a?, {0x140000307c0?, 0x14005b1f710?, 0xfffffffffffffff9?}}, ...)
        /Users/thaodtp/Documents/work/projects/FDO/FA/fdo-fido-conformance-server/core/device/genvoucher.go:51 +0x268
github.com/fido-alliance/fdo-fido-conformance-server/core/device.NewVirtualDeviceAndVoucher({{}, {0x1400009c910, 0x3, 0x3}, {0x14000190240, 0x8a, 0x8a}, 0x5, 0xfffffffffffffff9, {{}, ...}, ...}, ...)
```

## What part of the spec are you testing?

- [ ] Rendezvous Server
- [x] Device Onboarding Service
- [ ] Device Implementation

## What protocol are having issue with?

- [ ] TO0
- [ ] TO1
- [ ] TO2

## Issue description
 - The issue occurs when calling API "/api/dot/api"
 
<img width="673" alt="image" src="https://github.com/fido-alliance/fdo-fido-conformance-server/assets/81215424/d26b536d-e605-4d08-9f77-3d45a3d70f37">

**Comment by herrjemand** [comment]
Resolved
